version: '3'

services:
 web:
   image: webdevops/php-apache:ubuntu-16.04
   ports:
    - 8805:80
    - 448:443
   volumes:
    - ./web:/app
   links:
    - mysql
   environment:
    WEB_DOCUMENT_ROOT: /app/web
   container_name: craftcms_web
 mysql:
   image: mysql:5.6
   restart: always
   env_file:
    - .env
   container_name: craftcms_database
   ports:
    - 3309:3306
   volumes:
    - sql-data:/var/lib/mysql
volumes:
  sql-data:
